### PR TITLE
fix: add retry to network settings update

### LINKED ISSUE #239: Creating `supabase_settings` with network settings directly after `supabase_project` almost always fails
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When creating `supabase_settings` with network settings directly after `supabase_project`, the operation almost always fails.

Terraform / Opentofu code:

```
resource "supabase_project" "supabase_project" {
  organization_id   = var.supabase_organisation_id
  name              = var.supabase_project_name
  database_password = random_password.database_password.result
  # ...
}

resource "supabase_settings" "supabase_settings" {
  project_ref = supabase_project.supabase_project.id

  # Example: Allow access from all networks
  network = jsonencode({
    restrictions = [
      "0.0.0.0/0",
      "::/0"
    ]
  })

  # ...

  depends_on      = [supabase_project.supabase_project]
}
```

Error message:

```
* Failed to execute "tofu apply -auto-approve" in opentofu/backend
  ╷
  │ Error: Client Error
  │ 
  │   with supabase_settings.supabase_settings,
  │   on main.tf line 25, in resource "supabase_settings" "supabase_settings":
  │   25: resource "supabase_settings" "supabase_settings" {
  │ 
  │ Unable to update network settings, got status 500: {"message":"error adding
  │ pooler tenant for
  │ us-east-1/abc...","errorEventId":"123..."}
  ╵
```

When rerunning the pipeline, it always succeeds.

I've already added a 1-minute sleep between both operations which worked okayish for a while until last week. However, I don't consider a sleep-command a proper way to handle this case. The proper way in my opinion would be that the create-operation of the instance itself waits until it can be used or that the settings have some kind of internal async wait, retry or whatever.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create `supabase_settings` with network settings directly after `supabase_project`, see above

## Expected behavior

The creation of both resources always succeeds.

## Screenshots

None

## System information

- OS:
- Browser:
- Version of supabase-js:
- Version of Node.js:

## Additional context

None

### PR DESCRIPTION
**Pull request by JEETDESAI25**
## What kind of change does this PR introduce?

Adds retry handling for network settings updates.

## What is the current behavior?

Closes #239. Applying supabase_settings immediately after supabase_project frequently fails with HTTP 500 (error adding pooler tenant…) because the pooler tenant isn’t fully provisioned yet; users must rerun manually.

## What is the new behavior?

- updateNetworkConfig now wraps the API call in retry.RetryContext, retrying transient 500s for up to 5 minutes with debug logging on each retry.
- Added TestAccSettingsResource_NetworkRetry, which mocks a 500→201 flow to validate the retry path end-to-end.

## Additional context

Retry window is five minutes to give the pooler tenant time to finish provisioning; the issue noted one-minute sleeps were no longer sufficient, and other Terraform providers use 2–5 minute waits for similar propagation delays.

### CODE REVIEW

**Review by savme — COMMENTED** [review]
Thanks so much for the PR, @JEETDESAI25! This definitely solves the core issue. I think we should tweak the approach slightly, because retrying on any `500` might capture unrelated errors we probably don't want to retry.

We might be better off verifying that the project is in the `ACTIVE` state before moving forward with any related resources (in both `createProject` and `updateProject`). That way we'd avoid broad retries and still solve the underlying problem.

Happy to chat through the details if you'd like - just let me know!

**Comment by JEETDESAI25** [comment]
@savme Thanks for the review! You’re right about the blanket 500 retry and it could hide unrelated errors. My plan is to add a `waitForProjectActive` helper that polls GET /v1/projects/{ref} until the status is `ACTIVE_HEALTHY` or `ACTIVE_UNHEALTHY`, call it at the end of `createProject` and after `updateInstanceSize` and then remove the retry from `updateNetworkConfig`. That matches the current 5‑minute window but makes the readiness check explicit. Does this sound good?

**Comment by JEETDESAI25** [comment]
Thank you for guiding me, really appreciate your feedback. Please let me know if there's anything else I can adjust. @savme

File: internal/provider/utils.go [hunk 1]
```diff
@@ -18,3 +26,94 @@ func NullableToString[T ~string](n nullable.Nullable[T]) tftypes.String {
...
 }
+
+const projectActiveTimeout = 5 * time.Minute
+
+const statusUnknownTransient = "UNKNOWN_TRANSIENT"
+
+var knownProjectStatuses = map[api.V1ProjectWithDatabaseResponseStatus]bool{
+	// Target
+	api.V1ProjectWithDatabaseResponseStatusACTIVEHEALTHY: true,
+	// Pending
```
Comment (sweatybridge) [inline internal/provider/utils.go]: lets move this to a separate array for easier reuse

File: internal/provider/utils.go [hunk 2]
```diff
@@ -18,3 +26,94 @@ func NullableToString[T ~string](n nullable.Nullable[T]) tftypes.String {
 
 	return tftypes.StringNull()
 }
+
+const projectActiveTimeout = 5 * time.Minute
+
+const statusUnknownTransient = "UNKNOWN_TRANSIENT"
```
Comment (sweatybridge) [inline internal/provider/utils.go]: we can remove this custom status

File: internal/provider/utils.go [hunk 3]
```diff
@@ -18,3 +26,67 @@ func NullableToString[T ~string](n nullable.Nullable[T]) tftypes.String {
...
+				return nil, "", fmt.Errorf("unexpected status %d: %s", httpResp.StatusCode(), httpResp.Body)
+			}
+
+			status := string(httpResp.JSON200.Status)
+			tflog.Debug(ctx, "Waiting for project to become active", map[string]interface{}{
+				"project_ref": projectRef,
+				"status":      status,
+			})
+
+			for _, ts := range terminalProjectStatuses {
```
Comment (savme) [inline internal/provider/utils.go]: `slices.Contains`
